<a href="https://colab.research.google.com/github/Beta628427/Tesis/blob/master/Lucas___Cod/PCA_Cod_master_v2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CODIGO MASTER PCA _ BETA

## En escodigo encontraremos PCA aplicado a los datos mmc3

__ Versión 1.0 __

In [2]:
pip install mglearn

     |████████████████████████████████| 542kB 2.8MB/s 
  Created wheel for mglearn: filename=mglearn-0.1.7-py2.py3-none-any.whl size=582705 sha256=74670bc84554ea43bd85f1931fee557df637ea1ce8510e09f9632139df13ec10
  Stored in directory: /root/.cache/pip/wheels/74/cf/8d/04f4932d15854a36726c6210763c7127e62de28f5c8ddfcf3b
Successfully built mglearn


In [3]:
import gspread, sklearn, mglearn, time, pandas as pd, numpy as np, scipy as sc
import matplotlib.pyplot as plt
from oauth2client.client import GoogleCredentials
from google.colab import auth
from sklearn.decomposition import PCA
from IPython.display import clear_output

# Autoriza Drive_BETA
auth.authenticate_user()
gc = gspread.authorize(GoogleCredentials.get_application_default())

/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


### ¡Aquí! Almaceno toda la informacion del GoogleSheet < mmc3 > en una sola variable diccionario < dcc >


In [4]:
# Creamos la variable diccionario
sh = gc.open('mmc3') # Abro GoogleSheet < mmc3 >
#···············································································
wk_lista = sh.worksheets()                                           # Variables
dcc , dcc_art = {} , {}
ndatos = 101              # numeros de frames en este caso de 0-100 = 101 datos
target_colum = ['% Gait Cycle', 
                'joven_Natural-',   'joven_Natural',   'joven_Natural+', 
                'joven_XS-',        'joven_XS',        'joven_XS+', 
                'joven_S-',         'joven_S',         'joven_S+', 
                'joven_M-',         'joven_M',         'joven_M+', 
                'joven_L-',         'joven_L',         'joven_L+', 
                'joven_Toe-',       'joven_Toe',       'joven_Toe+', 
                'joven_Heel-',      'joven_Heel',      'joven_Heel+', 
                'joven_Ascending-', 'joven_Ascending', 'joven_Ascending+', 
                'joven_Descending-','joven_Descending','joven_Descending+',
                'viejo_Natural-',   'viejo_Natural',   'viejo_Natural+', 
                'viejo_XS-',        'viejo_XS',        'viejo_XS+', 
                'viejo_S-',         'viejo_S',         'viejo_S+', 
                'viejo_M-',         'viejo_M',         'viejo_M+', 
                'viejo_L-',         'viejo_L',         'viejo_L+', 
                'viejo_Toe-',       'viejo_Toe',       'viejo_Toe+', 
                'viejo_Heel-',      'viejo_Heel',      'viejo_Heel+', 
                'viejo_Ascending-', 'viejo_Ascending', 'viejo_Ascending+', 
                'viejo_Descending-','viejo_Descending','viejo_Descending+']
#···············································································
for i in range(1,5):                           # Nombre de las pestañas del mmc3
  _art_ = []
  wk = sh.worksheet(wk_lista[i].title)  
  rw = np.array(wk.get_all_values())
  k  = ""
  dcc[str(wk_lista[i].title)] = {}
  _f1 = 1                   # fila de inicio por articulacion
  _f2 = 102                 # fila final de articulacion 
  iii = 0
  dcc_art = {}
  for ii in range(1,rw[:,0].shape[0]):  # Nombre de las articulaciones del sheet
    j = str(rw[ii,0]) # nombre de la articulacion
    if str(k) == str(j): # cambio de nombre
      j = j
    else:
      _art_.append(j)
      if iii > 0:
        _f1 = (101 * iii) + 1                  # fila de inicio por articulacion
        _f2 = _f1 + 101                             # fila final de articulacion
      tabla = pd.DataFrame(rw[_f1:_f2,1::])
      tabla.columns = target_colum
      dcc_art[str(j)] = tabla
      dcc[str(wk_lista[i].title)] = dcc_art
      iii = iii + 1
    k = j 
pd.DataFrame(dcc)

Joint Rotations  ...                                        Joint Power
Pelvic Ant/Posterior Tilt         % Gait Cycle joven_Natural-  ... viejo_Des...  ...                                                NaN
Pelvic Up/Down Obliquity          % Gait Cycle joven_Natural-  ... viejo_Des...  ...                                                NaN
Pelvic Int/External Rotation      % Gait Cycle joven_Natural-  ... viejo_Des...  ...                                                NaN
Hip Flex/Extension                % Gait Cycle joven_Natural-  ... viejo_Des...  ...                                                NaN
Hip Ad/Abduction                  % Gait Cycle joven_Natural-  ... viejo_Des...  ...                                                NaN
Hip Int/External Rotation         % Gait Cycle joven_Natural-  ... viejo_Des...  ...                                                NaN
Knee Flex/Extension               % Gait Cycle joven_Natural-  ... viejo_Des...  ...                                                NaN
Ankle Dorsi/Plantarflexion        % Gait Cycle joven_Natural-  ... viejo_Des...  ...                                                NaN
Thigh Flex/Extension              % Gait Cycle joven_Natural-  ... viejo_Des...  ...                                                NaN
Thigh Ad/Abduction                % Gait Cycle joven_Natural-  ... viejo_Des...  ...                                                NaN
Shank  Flex/Extension             % Gait Cycle joven_Natural-  ... viejo_Des...  ...                                                NaN
Shank  Ad/Abduction               % Gait Cycle joven_Natural-  ... viejo_Des...  ...                                                NaN
Foot Flex/Extension               % Gait Cycle joven_Natural-  ... viejo_Des...  ...                                                NaN
Foot Int/External Rotation        % Gait Cycle joven_Natural-  ... viejo_Des...  ...                                                NaN
Anterior/Posterior                                                          NaN  ...                                                NaN
Medio/Lateral                                                               NaN  ...                                                NaN
Vertical                                                                    NaN  ...                                                NaN
Hip Ext/Flexion                                                             NaN  ...                                                NaN
Hip Ab/Adduction                                                            NaN  ...                                                NaN
Knee Ext/Flexion                                                            NaN  ...                                                NaN
Knee Ab/Adduction                                                           NaN  ...                                                NaN
Hip                                                                         NaN  ...      % Gait Cycle joven_Natural-  ... viejo_Des...
Knee                                                                        NaN  ...      % Gait Cycle joven_Natural-  ... viejo_Des...
Ankle                                                                       NaN  ...      % Gait Cycle joven_Natural-  ... viejo_Des...

[24 rows x 4 columns]

In [5]:
dcc['Joint Rotations']['Pelvic Ant/Posterior Tilt']

% Gait Cycle joven_Natural-  ... viejo_Descending viejo_Descending+
0             0%           -7.3  ...             -9.2              -2.5
1             1%           -7.2  ...             -9.2              -2.5
2             2%           -7.2  ...             -9.3              -2.6
3             3%           -7.2  ...             -9.4              -2.7
4             4%           -7.1  ...             -9.5              -2.8
..           ...            ...  ...              ...               ...
96           96%           -7.4  ...             -9.9              -2.4
97           97%           -7.4  ...             -9.9              -2.4
98           98%           -7.3  ...             -9.9              -2.4
99           99%           -7.2  ...            -10.0              -2.4
100         100%           -7.1  ...            -10.0              -2.5

[101 rows x 55 columns]

In [6]:
dcc['Ground Reaction Forces']

{'Anterior/Posterior':     % Gait Cycle joven_Natural-  ... viejo_Descending viejo_Descending+
 0             0%           0.00  ...             0.00              0.00
 1             1%          -0.07  ...            -0.02              0.00
 2             2%          -0.11  ...            -0.05             -0.02
 3             3%          -0.18  ...            -0.05             -0.03
 4             4%          -0.21  ...            -0.06             -0.03
 ..           ...            ...  ...              ...               ...
 96           96%           0.00  ...             0.00              0.00
 97           97%           0.00  ...             0.00              0.00
 98           98%           0.00  ...             0.00              0.00
 99           99%           0.00  ...             0.00              0.00
 100         100%           0.00  ...             0.00              0.00
 
 [101 rows x 55 columns],
 'Medio/Lateral':     % Gait Cycle joven_Natural-  ... viejo_Descending vi

In [0]:
dcc['Joint Moments']

In [0]:
dcc['Joint Power']

## Función de realizar numeros aleatorios con una media y una desviacion estandar especifica


In [0]:
# PROCESO DE GENERAR NUMEROS ALEATORIOS CON PROMEDIO Y DESVIACION ESTANDAR 
# DESEADOS
#···············································································
num_samples     = 20     # Numero de numeros aleatorios a generar
desired_mean    = -2.8   # promedio de numeros aleatorios
desired_std_dev = 8.9    # Desviacion estandar a numeros aleatorios a generar
#···············································································
# Funcion de variables aleatorias con media y desviacion estandar
def var_alea (num_samples,desired_mean,desired_std_dev):
  samples = np.random.normal(loc=0.0, scale=desired_std_dev, size=num_samples)
  actual_mean = np.mean(samples)
  actual_std = np.std(samples)
  #print("Initial samples stats   : mean = {:.4f} stdv = {:.4f}".
  #      format(actual_mean, actual_std))
  zero_mean_samples = samples - (actual_mean)
  zero_mean_mean = np.mean(zero_mean_samples)
  zero_mean_std = np.std(zero_mean_samples)
  #print("True zero samples stats : mean = {:.4f} stdv = {:.4f}".
  #      format(zero_mean_mean, zero_mean_std))
  scaled_samples = zero_mean_samples * (desired_std_dev/zero_mean_std)
  scaled_mean = np.mean(scaled_samples)
  scaled_std = np.std(scaled_samples)
  #print("Scaled samples stats    : mean = {:.4f} stdv = {:.4f}".
  #      format(scaled_mean, scaled_std))
  final_samples = scaled_samples + desired_mean
  final_mean = np.mean(final_samples)
  final_std = np.std(final_samples)
  #print("Final samples stats     : mean = {:.4f} stdv = {:.4f}".
  #      format(final_mean, final_std))
  #print(final_samples)
  return(final_samples)

### ¡Aquí! vuelvo una tabla en 20 tablas que almacena las variables tanto de jovenes como las de viejos de los targets < "Natural","XS","S","M","L","Toe","Heel","Ascending","Descending" > con media y desviacion dada:

#### 1) la media es el valor medio de cada target
#### 2) la desviacion estandar es la suma de los valores absolutos de la desviacion estandar positima mas la negativa.

#### Nota····································································
#### solo salieron 25 lineas de codigo XD solo que para que se vea mas bonito consume mas lineas 

\\(·w·)/


In [0]:
#···············································································
# Variables diccionario de las tablas de 20 personas para jovenes y adultas
per = [""   ,"p1" ,"p2" ,"p3" ,"p4" ,"p5" ,"p6" ,"p7" ,"p8" ,"p9" ,"p10",
       "p11","p12","p13","p14","p15","p16","p17","p18","p19","p20"]
personas= {per[1]:[] ,per[2]:[] ,per[3]:[] ,per[4]:[] ,per[5] :[],
           per[6]:[] ,per[7]:[] ,per[8]:[] ,per[9]:[] ,per[10]:[],
           per[11]:[],per[12]:[],per[13]:[],per[14]:[],per[15]:[],
           per[16]:[],per[17]:[],per[18]:[],per[19]:[],per[20]:[]}
target_colum_ = ['% Gait Cycle','joven_Natural','joven_XS',
                 'joven_S','joven_M','joven_L','joven_Toe','joven_Heel', 
                 'joven_Ascending','joven_Descending','viejo_Natural',
                 'viejo_XS','viejo_S','viejo_M','viejo_L','viejo_Toe',
                 'viejo_Heel','viejo_Ascending','viejo_Descending']
for i in range(1,21):
  personas[per[i]] = pd.DataFrame(np.zeros((101,19)))
  personas[per[i]].columns = target_colum_
#···············································································

In [9]:
personas['p1']

% Gait Cycle  joven_Natural  ...  viejo_Ascending  viejo_Descending
0             0.0            0.0  ...              0.0               0.0
1             0.0            0.0  ...              0.0               0.0
2             0.0            0.0  ...              0.0               0.0
3             0.0            0.0  ...              0.0               0.0
4             0.0            0.0  ...              0.0               0.0
..            ...            ...  ...              ...               ...
96            0.0            0.0  ...              0.0               0.0
97            0.0            0.0  ...              0.0               0.0
98            0.0            0.0  ...              0.0               0.0
99            0.0            0.0  ...              0.0               0.0
100           0.0            0.0  ...              0.0               0.0

[101 rows x 19 columns]

In [0]:
#···············································································
__tabla_art = {}
for i in range(1,5):                           # Nombre de las pestañas del mmc3
  __art_ = {}
  wk = sh.worksheet(wk_lista[i].title)  
  rw = np.array(wk.get_all_values())
  for ii in range(1,rw[:,0].shape[0]):  # Nombre de las articulaciones del sheet
    j = str(rw[ii,0]) # nombre de la articulacion
    if str(k) == str(j): # cambio de nombre
      j = j
    else:
      __art_[str(j)] = {}
      #__art_.append(j)
    k = j
  if i == 1: __tabla_art[str(wk_lista[i].title)] = __art_ 
  if i == 2: __tabla_art[str(wk_lista[i].title)] = __art_
  if i == 3: __tabla_art[str(wk_lista[i].title)] = __art_
  if i == 4: __tabla_art[str(wk_lista[i].title)] = __art_
#···············································································

In [11]:
dcc['Joint Rotations']['Pelvic Ant/Posterior Tilt']

% Gait Cycle joven_Natural-  ... viejo_Descending viejo_Descending+
0             0%           -7.3  ...             -9.2              -2.5
1             1%           -7.2  ...             -9.2              -2.5
2             2%           -7.2  ...             -9.3              -2.6
3             3%           -7.2  ...             -9.4              -2.7
4             4%           -7.1  ...             -9.5              -2.8
..           ...            ...  ...              ...               ...
96           96%           -7.4  ...             -9.9              -2.4
97           97%           -7.4  ...             -9.9              -2.4
98           98%           -7.3  ...             -9.9              -2.4
99           99%           -7.2  ...            -10.0              -2.4
100         100%           -7.1  ...            -10.0              -2.5

[101 rows x 55 columns]

In [22]:
xxx = 0 
for ii in range(1,5):
  _sheet = str(wk_lista[ii].title)
  for i in range(pd.DataFrame(__tabla_art[_sheet]).shape[1]):
    _artic = list(__tabla_art[_sheet])[i]
    j_v = ["joven","viejo"]            # Lleno las distinatas tablas de personas
    tag = ["Natural","XS","S","M","L","Toe","Heel","Ascending","Descending"]
    # Armar el tag
    for _j_v in j_v:
      xxx = 0
      for _tag in tag:
        vari = _j_v+"_"+_tag
        xxx = xxx + 1
        print(_sheet + " => " + _artic + "=>" + str(xxx))
        for m in range(dcc[_sheet][_artic].shape[0]):
          mean = dcc[_sheet ][_artic][vari][i]
          _mas = dcc[_sheet ][_artic][vari+"+"][i]
          _men = dcc[_sheet ][_artic][vari+"-"][i]
          DE   = abs(float(_mas))+abs(float(_men))
          NP   = pd.DataFrame(per).shape[0]-1 # numero de personas    
          num_gener = var_alea(NP,float(mean),DE)# genero los numeros aleatorios
          # Comprovamos valores demedia y desviacion estandar
          media = np.mean(num_gener)
          DEE = np.std(num_gener)
          for _per in range(1,pd.DataFrame(per).shape[0]):
            personas[per[_per]][vari][m] = num_gener[_per-1]
            __tabla_art[_sheet][_artic] = personas

Joint Rotations => Pelvic Ant/Posterior Tilt=>1
Joint Rotations => Pelvic Ant/Posterior Tilt=>2
Joint Rotations => Pelvic Ant/Posterior Tilt=>3
Joint Rotations => Pelvic Ant/Posterior Tilt=>4
Joint Rotations => Pelvic Ant/Posterior Tilt=>5
Joint Rotations => Pelvic Ant/Posterior Tilt=>6
Joint Rotations => Pelvic Ant/Posterior Tilt=>7
Joint Rotations => Pelvic Ant/Posterior Tilt=>8
Joint Rotations => Pelvic Ant/Posterior Tilt=>9
Joint Rotations => Pelvic Ant/Posterior Tilt=>1
Joint Rotations => Pelvic Ant/Posterior Tilt=>2
Joint Rotations => Pelvic Ant/Posterior Tilt=>3
Joint Rotations => Pelvic Ant/Posterior Tilt=>4
Joint Rotations => Pelvic Ant/Posterior Tilt=>5
Joint Rotations => Pelvic Ant/Posterior Tilt=>6
Joint Rotations => Pelvic Ant/Posterior Tilt=>7
Joint Rotations => Pelvic Ant/Posterior Tilt=>8
Joint Rotations => Pelvic Ant/Posterior Tilt=>9
Joint Rotations => Pelvic Up/Down Obliquity=>1
Joint Rotations => Pelvic Up/Down Obliquity=>2
Joint Rotations => Pelvic Up/Down Obliquit

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:17: RuntimeWarning: invalid value encountered in double_scalars


Ground Reaction Forces => Anterior/Posterior=>3
Ground Reaction Forces => Anterior/Posterior=>4
Ground Reaction Forces => Anterior/Posterior=>5
Ground Reaction Forces => Anterior/Posterior=>6
Ground Reaction Forces => Anterior/Posterior=>7
Ground Reaction Forces => Anterior/Posterior=>8
Ground Reaction Forces => Anterior/Posterior=>9
Ground Reaction Forces => Anterior/Posterior=>1
Ground Reaction Forces => Anterior/Posterior=>2
Ground Reaction Forces => Anterior/Posterior=>3
Ground Reaction Forces => Anterior/Posterior=>4
Ground Reaction Forces => Anterior/Posterior=>5
Ground Reaction Forces => Anterior/Posterior=>6
Ground Reaction Forces => Anterior/Posterior=>7
Ground Reaction Forces => Anterior/Posterior=>8
Ground Reaction Forces => Anterior/Posterior=>9
Ground Reaction Forces => Medio/Lateral=>1
Ground Reaction Forces => Medio/Lateral=>2
Ground Reaction Forces => Medio/Lateral=>3
Ground Reaction Forces => Medio/Lateral=>4
Ground Reaction Forces => Medio/Lateral=>5
Ground Reaction F

In [36]:
sh = gc.open('mmc3')
wk = sh.worksheet('Joint Rotations') 
rw = np.array(wk.get_all_values())

y2 = np.zeros((360,0))
for ii in range(1,rw[:,0].shape[0]):  # Nombre de las articulaciones del sheet
    _a = str(rw[ii,0]) # nombre de la articulacion
    if str(k) == str(_a): # cambio de nombre
      _a = _a
    else:

      x2 = np.zeros((0,101))
      for i in range(1,21):
        _p = "p"+str(i)
        x1 = np.array(__tabla_art['Joint Rotations'][_a][_p].iloc[:,1:].T)
        x2 = np.concatenate((x2,x1),axis=0)
      y1 = x2
      y2 = np.concatenate((y2,y1),axis=1)
    k = _a

print(y2.shape)
pd.DataFrame(y2)

(360, 1414)


0         1         2     ...      1411      1412      1413
0    0.122669  0.142561  0.050308  ... -0.100659 -0.063867 -0.271084
1    0.059239 -0.324023 -0.064102  ...  0.008764  0.080390  0.077931
2   -0.047080 -0.015330 -0.077243  ... -0.106051  0.011917 -0.073379
3   -0.193074 -0.109519  0.069680  ... -0.303419 -0.123202  0.059589
4    0.167213  0.206374 -0.028745  ...  0.353907 -0.143392  0.166848
..        ...       ...       ...  ...       ...       ...       ...
355  0.625371  0.002372 -0.284180  ... -0.415912 -0.571646 -0.506120
356 -4.146329  4.132242 -6.388549  ... -2.555707 -1.775154  1.535275
357 -0.349481  0.175260 -0.426618  ... -0.497154 -0.222061 -0.153298
358 -0.219471 -0.166881 -0.134573  ...  0.478245 -0.123796  0.053189
359 -6.147777 -0.811373 -9.163538  ... -4.742258  1.249220  1.718112

[360 rows x 1414 columns]

In [50]:
Y = []
for i in range(20):
  for j in range(18):
    Y.append(j)
Y =  np.array(Y)[:,np.newaxis]
print(Y.shape)

(360, 1)


In [200]:
X = y2
Y = pd.DataFrame(Y)
Y.columns = [1414]
df = pd.concat([pd.DataFrame(X),Y], axis=1)
df
np.random.seed(42)
rndperm = np.random.permutation(df.shape[0])
df = df.loc[rndperm,:]
X = df.loc[:,:1413]
y = df.loc[:,1414]

from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
y = mlb.fit_transform(y.astype('str'))
print(y)
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)
print(X_train)
print(y_train)



[[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]]
(270, 1414) (270, 10)
(90, 1414) (90, 10)
         0         1         2     ...      1411      1412      1413
63   0.184485 -0.107995 -0.323587  ...  0.052304 -0.078964  0.158446
79   0.085640  0.392487  0.261221  ... -1.016888 -0.179287  0.051807
343  0.062227 -0.162454  0.144234  ...  0.297034 -0.010358 -0.030795
167  0.817623 -3.831351  4.637998  ... -3.135810  1.161829 -5.560009
65  -0.266578 -0.151950 -0.279531  ...  0.287279 -0.048350  0.093601
..        ...       ...       ...  ...       ...       ...       ...
197  2.213976 -4.967378 -1.448889  ...  4.637740  3.261522 -7.194397
355  0.625371  0.002372 -0.284180  ... -0.415912 -0.571646 -0.506120
230  8.115980 -0.952107 -5.737421  ... -5.028338  5.047133  4.722127
87  -0.443928 -0.581495 -0.425415  ... -0.228515 -0.255101 -0.143681
208  0.081005 -0.047790  0.200677  ...  0.012655 -0.126130 -0.284608

[270 rows

In [0]:





from sklearn.decomposition import PCA
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.neural_network import MLPClassifier


pca = PCA()
svc = SVC(kernel='poly',C=10,gamma=0.01)
clf = OneVsRestClassifier(svc)
pipe = Pipeline(steps=[('pca', pca),('clf',clf)])

# Parameters of pipelines can be set using ‘__’ separated parameter names:
param_grid = {
    'pca__n_components': [2,5,8,12,15,17,25,30, 45, 64],
}
search = GridSearchCV(pipe, param_grid, n_jobs=-1)
search.fit(X_train, y_train)
print("Best parameter (CV score=%0.3f):" % search.best_score_)
print(search.best_params_)
# Plot the PCA spectrum
pca.fit(X_train)

fig, (ax0, ax1) = plt.subplots(nrows=2, sharex=True, figsize=(6, 6))
ax0.plot(np.arange(1, pca.n_components_ + 1),
         pca.explained_variance_ratio_, '+', linewidth=2)
ax0.set_ylabel('PCA explained variance ratio')

ax0.axvline(search.best_estimator_.named_steps['pca'].n_components,
            linestyle=':', label='n_components chosen')
ax0.legend(prop=dict(size=12))

# For each number of components, find the best classifier results
results = pd.DataFrame(search.cv_results_)
components_col = 'param_pca__n_components'
best_clfs = results.groupby(components_col).apply(
    lambda g: g.nlargest(1, 'mean_test_score'))

best_clfs.plot(x=components_col, y='mean_test_score', yerr='std_test_score',
               legend=False, ax=ax1)
ax1.set_ylabel('Classification accuracy (val)')
ax1.set_xlabel('n_components')

plt.xlim(-1, 70)

plt.tight_layout()
plt.show()


In [202]:
%pip install xgboost
import xgboost as xgb
from sklearn.decomposition import PCA
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.neural_network import MLPClassifier

pca = PCA()
clf = OneVsRestClassifier(xgb(n_jobs=-1, max_depth=4,num_class= 18))
pipe = Pipeline(steps=[('pca', pca),('clf',clf)])

# Parameters of pipelines can be set using ‘__’ separated parameter names:
param_grid = {
    'pca__n_components': [2,5,8,12,15,17,25,30, 45, 64],
}
search = GridSearchCV(pipe, param_grid, n_jobs=-1)

search.fit(X_train, y_train)
print("Best parameter (CV score=%0.3f):" % search.best_score_)
print(search.best_params_)
# Plot the PCA spectrum
pca.fit(X_train)

fig, (ax0, ax1) = plt.subplots(nrows=2, sharex=True, figsize=(6, 6))
ax0.plot(np.arange(1, pca.n_components_ + 1),
         pca.explained_variance_ratio_, '+', linewidth=2)
ax0.set_ylabel('PCA explained variance ratio')

ax0.axvline(search.best_estimator_.named_steps['pca'].n_components,
            linestyle=':', label='n_components chosen')
ax0.legend(prop=dict(size=12))

# For each number of components, find the best classifier results
results = pd.DataFrame(search.cv_results_)
components_col = 'param_pca__n_components'
best_clfs = results.groupby(components_col).apply(
    lambda g: g.nlargest(1, 'mean_test_score'))

best_clfs.plot(x=components_col, y='mean_test_score', yerr='std_test_score',
               legend=False, ax=ax1)
ax1.set_ylabel('Classification accuracy (val)')
ax1.set_xlabel('n_components')

plt.xlim(-1, 70)

plt.tight_layout()
plt.show()


TypeError: ignored